export enum ErrorCodes {
  // User errors
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_USER_DATA = 'INVALID_USER_DATA',

  // Auth errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Image errors
  IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
  IMAGE_UPLOAD_FAILED = 'IMAGE_UPLOAD_FAILED',
  INVALID_IMAGE_FORMAT = 'INVALID_IMAGE_FORMAT',

  // General errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
}
